### PR TITLE
Overhaul datafile inclusion/generation

### LINKED ISSUE #5: Library gives fatal error when unable to contact unicode.org
If `utils.get()` is run too many times, **unicode.org** may throttle or even blacklist the server.  In this case, `categories.py` fails with the error `Datafile not found, datafile generation failed!`  The timeout on **unicode.org** is reported when the file is run from the command line, but not when it is called from `django-registration`.

I'm open to various ways of avoiding the timeout issue in the first place.  Two ideas are allowing users to specify a path to cached copies of `categories.json` and `confusables.json` (the release on PyPI does not include these files), or to a mirror copy of those files on a different server.

Regardless, I suggest that `utils.get()` raise an error if it is unable to contact **unicode.org**, so that the errors are more informative.

### PR DESCRIPTION
**Pull request by rpkilby**
Hi @vhf. With this PR, I'm aiming to change the way data files are package/generated. A few pain points:

- Generating data files relative to the current working directory is not usually desirable.
- If the data files don't exist, the package attempts to generate them. Right now, this is failing for me as `unicode.org` seems to be down.

Larger changes:
- Fixes #5
- Changed file paths to be relative to the `confusable_homoglyphs` package directory instead of the user's current working directory. 
- Data files are now distributed with the packaging.
- Fixes tests so that they use the installed distribution instead of the local files. (originally, the data files were erroneously showing up during testing, despite note being included in the distribution). 
- Moves the data file generation into a simple CLI. This way, users have a method for controlling when the data files are updated. 
- Since the data files are now included in the distribution, I made the cli optional. its dependencies can be installed with the `cli` bundle. eg, `pip install confusable_homoglyphs[cli]`

I tried to break changes into discrete commits, which should have more detail.

### CODE REVIEW

**Comment by vhf** [comment]
Hey, that's awesome, thanks a lot!

I reviewed each commit, it's looking really good.

Could you please add `# -*- coding: utf-8 -*-` at the beginning of `cli.py`? Otherwise tests won't pass w/py2, at least on my system: `SyntaxError: Non-ASCII character '\xe2' in file […]confusable_homoglyphs/cli.py on line 80, but no encoding declared;`

**Comment by rpkilby** [comment]
Added.

**Comment by vhf** [comment]
Awesome, thanks a lot!

What do you think, would you publish it as a new major version although I don't think it's breaking backwards compatibility, or publish as `2.1.0`? I think `2.1.0` would be better.

**Comment by rpkilby** [comment]
Side note - docs need to be updated. Should I add it to the PR, or would you prefer to take care of that?

**Comment by vhf** [comment]
I'd appreciate it if you could add docs changes to this PR! 👍

**Comment by rpkilby** [comment]
> What do you think, would you publish it as a new major version although I don't think it's breaking backwards compatibility, or publish as `2.1.0`? I think `2.1.0` would be better.

I'm somewhat conflicted. *Strictly* speaking, this is a forwards incompatible change, given that the `generate()` functions are no longer present on the respective modules, and they're *technically* part of the public API. *Practically* speaking, it's probably irrelevant - I doubt many people were using the `generate()` functions in their own code. 

That all said, how the data files are managed is completely different, and it's no longer necessary for users to commit them to their own packages. I'd say `3.0`?

**Comment by rpkilby** [comment]
Okay - added a brief note about the CLI in the usage docs. Didn't realize that the API reference is auto generated, so there's nothing to do there.

**Comment by vhf** [comment]
Thanks, I really appreciate this!

**Comment by vhf** [comment]
Released as `3.0.0`!

**Pull request merged**
